---
title: "Osa Conservation: Tracker Checker"

author:
  - Chris Beirne


site: bookdown::test-bookdown
output: bookdown::gitbook
documentclass: book
biblio-style: apalike
link-citations: yes
---

# Tracker status checker

```{r, echo=F, message=F, include=F}
library(move)
library(dplyr)
library(leaflet)
library(sf)
library(viridis)
library(kableExtra)
library(lubridate)

loginStored <- movebankLogin(username="ChrisBeirne", password="EcuadorG11")

# Get animals
animals <-getMovebankAnimals(study=1573471517,login=loginStored)
# For some reason they are duplicated
animals[duplicated(animals)==F,]
# They vary by the field "sensor_type_id"
animals <- animals[animals$sensor_type_id==653,]




# Get last 2 weeks
t <- now("America/Costa_Rica")

dat <- getMovebankData(study=1573471517, login=loginStored,  removeDuplicatedTimestamps=TRUE,
                       timestamp_start=t-as.difftime(14,units='days'))

# Convery move stack to dataframe
dat <- as.data.frame(dat)

# Convert dat to costa rica time
dat$timestamp <- with_tz(dat$timestamp, tzone = "America/Costa_Rica")


```

*Last updated: `r now(tzone = "America/Costa_Rica")`*


```{r, include=F}
# Add the location data


dat <- left_join(dat, animals[, c("tag_id", "animalName")])
# Sort the names out

dat$animalName <- sub('\\_.*', '', dat$animalName)
# Add in the taxonomic group
dat$animalName <- paste0(dat$animalName, "_", sub('\\ .*', '', dat$taxon_canonical_name))

# Add a country column
dat$country <- dat$location_lat<0
dat$country[dat$country==T] <- "peru"
dat$country[dat$country==F] <- "costa_rica"
#table(dat$country)



# Costa rica

# Convert to shapefiles
dat <- dat[order(dat$animalName),]


lfc <- do.call(st_sfc,
              lapply(split(dat, dat$animalName),
                     function(d){st_linestring(as.matrix(d[,c("location_long", "location_lat")]))}))
dat_shp <- st_sf(data.frame(animalName=levels(factor(dat[,"animalName"])), geom=lfc))

#
#plot(dat$location_long[dat$country=="costa_rica"], dat$location_lat[dat$country=="costa_rica"])
#plot(st_geometry(dat_shp), add=T)




sp_dat <- dat[,c("animalName",    "country", "taxon_canonical_name" )]
sp_dat <- sp_dat[duplicated(sp_dat)==F,]

# add back in the metadata
dat_shp  <- left_join(dat_shp,sp_dat)

```

**Time since last check-in**

The data was requested at `r now(tzone = "America/Costa_Rica")`.

```{r, echo=F, include=F}
# Last location and time since present
dat$diff_time <- round(as.numeric(difftime(t, dat$timestamp, units="hours")),1)

last_obs <- dat %>% group_by(animalName) %>% summarize(hours_since_fix=min(diff_time))


last_sum  <- dat %>% 
  group_by(animalName) %>%
  slice(which.max(timestamp))


tmp <- last_sum[, c("animalName","country", "timestamp", "diff_time")]
colnames(tmp)[colnames(tmp)=="diff_time"] <- "time_since_checkin_h"
colnames(tmp)[colnames(tmp)=="timestamp"] <- "last_timestamp"
tmp <- tmp[order(tmp$country, tmp$time_since_checkin_h),]


```


```{r}
tmp %>%
  kbl() %>%
  kable_styling()
```



**Costa Rica**

```{r, echo=F}
tmp <- dat[dat$country=="costa_rica",]
tmp_shp <- dat_shp[dat_shp$country=="costa_rica",]


# First lets choose a category to colour
tmp[,"animalName"] <- factor(tmp[,"animalName"])
tmp_shp$animalName <- factor(tmp_shp$animalName)

col.cat <- turbo(length(levels(tmp[,"animalName"])))
# Add it to the dataframe
tmp$colours <- col.cat[tmp[,"animalName"]]
tmp_shp$colours <- col.cat[tmp_shp$animalName]



m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Stamen.TonerLite, group="Simple") %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$Esri.WorldTopoMap, group="OS") %>%     
  addCircleMarkers(lng=tmp$location_long, lat=tmp$location_lat,
                   # Colour the markers depending on the 'feature type'
                   color=tmp$colours,
                   radius=3,
                   stroke=F,
                   # Add a popup of the deployment code 
                   popup=paste(tmp$animalName, tmp$timestamp)) %>%
  addPolylines(data=tmp_shp, color = tmp_shp$colours, weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5) %>% 
  # Add a legend explaining what is going on
  addLegend("bottomright", colors = col.cat,  labels = levels(tmp[,"animalName"]),
            title = "Name",
            labFormat = labelFormat(prefix = "$"),
            opacity = 1
  ) %>%
  # add a layer control box to toggle between the layers
  addLayersControl(
    baseGroups = c("Simple", "Satellite", "OS"),
    options = layersControlOptions(collapsed = FALSE)
  )
m
```

**Peru**

```{r, echo=F}
tmp <- dat[dat$country=="peru",]
tmp_shp <- dat_shp[dat_shp$country=="peru",]


# First lets choose a category to colour
tmp[,"animalName"] <- factor(tmp[,"animalName"])
tmp_shp$animalName <- factor(tmp_shp$animalName)

col.cat <- turbo(length(levels(tmp[,"animalName"])))
# Add it to the dataframe
tmp$colours <- col.cat[tmp[,"animalName"]]
tmp_shp$colours <- col.cat[tmp_shp$animalName]



m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Stamen.TonerLite, group="Simple") %>%
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$Esri.WorldTopoMap, group="OS") %>%     
  addCircleMarkers(lng=tmp$location_long, lat=tmp$location_lat,
                   # Colour the markers depending on the 'feature type'
                   color=tmp$colours,
                   radius=3,
                   stroke=F,
                   # Add a popup of the deployment code 
                   popup=paste(tmp$animalName, tmp$timestamp)) %>%
  addPolylines(data=tmp_shp, color = tmp_shp$colours, weight = 1, smoothFactor = 0.5,
              opacity = 1.0, fillOpacity = 0.5) %>% 
  # Add a legend explaining what is going on
  addLegend("bottomright", colors = col.cat,  labels = levels(tmp[,"animalName"]),
            title = "Name",
            labFormat = labelFormat(prefix = "$"),
            opacity = 1
  ) %>%
  # add a layer control box to toggle between the layers
  addLayersControl(
    baseGroups = c("Simple", "Satellite", "OS"),
    options = layersControlOptions(collapsed = FALSE)
  )
m
```